### ISSUE TITLE
athom without relay will not compile with esphome 2025.9.0

### ISSUE THREAD

**Issue by dmshimself** [athom-tech/athom-configs#131]
Compiling an 'athom without relay' gives the following errors in esphome 2025.9.0  (Previous version worked fine).  I've cleaned the installation files and rebuilt, but that doesn't help.  Other esphome devices such as the athom 4-channel relay compile just fine.

> 

In file included from /root/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266mDNS/src/ESP8266mDNS.h:48,
                 from /root/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266mDNS/src/ESP8266mDNS.cpp:23:
/root/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266mDNS/src/LEAmDNS.h:116:10: fatal error: WiFiUdp.h: No such file or directory

*****************************************************************
* Looking for WiFiUdp.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:WiFiUdp.h"
* Web  > https://registry.platformio.org/search?q=header:WiFiUdp.h
*
*****************************************************************

  116 | #include "WiFiUdp.h"
      |          ^~~~~~~~~~~
compilation terminated.
*** [.pioenvs/athom-without-relay-plug-5755de/lib0d3/ESP8266mDNS/ESP8266mDNS.cpp.o] Error 1

**Comment by bdleung** [comment]
same error for athom-smart-plug-v2, garage door opener and presence sensor. 

Similar to OP, my athom single x1 relay compiles fine.

**Comment by BeebleZap** [comment]
I also have same error for athom-smart-plug-v2

**Comment by BeebleZap** [comment]
Also have the following errors for athom-smart-plug-v2
Compiling .pioenvs/breville/src/esphome/components/light/addressable_light.cpp.o
src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.cpp:22:25: warning: 'const esphome::LogString* esphome::gpio::gpio_mode_to_string(bool)' defined but not used [-Wunused-function]
   22 | static const LogString *gpio_mode_to_string(bool use_interrupt) {
      |                         ^~~~~~~~~~~~~~~~~~~
src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.cpp:9:25: warning: 'const esphome::LogString* esphome::gpio::interrupt_type_to_string(esphome::gpio::InterruptType)' defined but not used [-Wunused-function]
    9 | static const LogString *interrupt_type_to_string(gpio::InterruptType type) {
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~

**Comment by effevee** [comment]
same errors here with esphome 2025.9.0 while recompiling athom-smart-plug-v2 and athom-norelay-plug. 

Compiling .pioenvs/athom-no-relay-plug-v2-ebd29c/lib3ff/ESP8266mDNS/ESP8266mDNS.cpp.o
In file included from /data/cache/platformio/packages/framework-arduinoespressif8266/libraries/ESP8266mDNS/src/ESP8266mDNS.h:48,
                 from /data/cache/platformio/packages/framework-arduinoespressif8266/libraries/ESP8266mDNS/src/ESP8266mDNS.cpp:23:
/data/cache/platformio/packages/framework-arduinoespressif8266/libraries/ESP8266mDNS/src/LEAmDNS.h:116:10: fatal error: WiFiUdp.h: No such file or directory

*****************************************************************
* Looking for WiFiUdp.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:WiFiUdp.h"
* Web  > https://registry.platformio.org/search?q=header:WiFiUdp.h
*
*****************************************************************

  116 | #include "WiFiUdp.h"
      |          ^~~~~~~~~~~
compilation terminated.
*** [.pioenvs/athom-no-relay-plug-v2-ebd29c/lib3ff/ESP8266mDNS/ESP8266mDNS.cpp.o] Error 1


Athom-garage-door compiled ok though.

**Comment by MaJerle** [comment]
Same here.

Are we sure it is athom issue? I am not so sure.

**Comment by thiagopinto-42q** [comment]
+1

**Comment by Bert-R** [comment]
It's an issue in ESPHome, see esphome/esphome#10770

**Comment by effevee** [comment]
> It's an issue in ESPHome, see [esphome/esphome#10770](https://github.com/esphome/esphome/issues/10770)

I can confirm it is indeed a problem with mdns in this esphome 2025.9.0 version. If you disable mdns in the yaml file, it compiles ok. 

BUT without mdns you will have to add manual ip settings to your yaml file or HA will not find your device anymore !!!!!

```
# esphome 2025.9.0 fatal error due to mdns ?
mdns:
  disabled: true

wifi:
  manual_ip:
    static_ip: 192.168.1.107
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.15
    dns2: 192.168.1.16

  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

```

**Comment by MaJerle** [comment]
Better to wait hot fix (it was fixed and will be released soon) and then update.

**Comment by hiraniha** [comment]
I have the same issue when using this package 

github://athom-tech/athom-configs/athom-presence-sensor.yaml

**Comment by Motya-HA** [comment]
@MaJerle  - define "soon", please

**Comment by MaJerle** [comment]
https://github.com/esphome/esphome/issues/10767#issuecomment-3305263575

:)

**Comment by tarontop** [comment]
It should be fixed now

**Comment by effevee** [comment]
ESPHome 25.9.1 has just been released with the fix; No more compilation problems :-)

**Comment by thgoncalves** [comment]
> ESPHome 25.9.1 has just been released with the fix; No more compilation problems :-)

Can confirm.. all good now
